# SSH Dashboard configuration
# Place this at ~/.ssh-dashboard/config.toml

log = "~/.ssh-dashboard/history.log"

[[commands]]
name = "port-forward-postgres"
command = "ssh -N -L 5432:127.0.0.1:5432 hughdbrown@10.0.0.211"
startup = true
interactive = true

[[commands]]
name = "port-forward-redis"
command = "ssh -N -L 6379:127.0.0.1:6379 hughdbrown@10.0.0.211"
startup = true
interactive = true

[[commands]]
name = "web-server"
command = "python3 -m http.server 8080"
startup = false
